import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import ReduxToolkitProvider from "@/redux/ReduxToolkitProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Topbar from "@/components/topbar/Topbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SHK",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxToolkitProvider>
          <NextTopLoader color="#6415ff" showSpinner={false} easing="ease" />
          <div style={{ paddingTop: "4rem", overflow: "auto" }}>
            <Topbar />
          </div>
          <div style={{ width: "95%", margin: "auto", marginTop: "20px" }}>{children}</div>
          <ToastContainer />
        </ReduxToolkitProvider>
      </body>
    </html>
  );
}
